<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <style>

        .clearfix:after {
            content: "";
            display: table;
            clear: both;
        }

        header {
            padding: 10px 0;
            margin-bottom: 20px;
            border-bottom: 1px solid #AAAAAA;
        }

        #company {
            float: right;
            text-align: right;
        }

        #details {
            margin-bottom: 50px;
        }

        h2.name {
            font-size: 1.4em;
            font-weight: normal;
            margin: 0;
        }

        #product {
            float: right;
            text-align: right;
        }

        #product h1 {
            color: #0087C3;
            font-size: 2.4em;
            line-height: 1em;
            font-weight: normal;
            margin: 0 0 10px 0;
        }

        #product .date {
            font-size: 1.1em;
            color: #777777;
        }

        table .billing {
            width: 100%;
            border-spacing: 0;
            margin-bottom: 20px;
        }

        table .billing th,
        table .billing td {
            padding: 5px 10px 7px 10px;
            background: #EEEEEE;
            text-align: center;
            border-bottom: 1px solid #FFFFFF;
        }

        table .billing th {
            white-space: nowrap;
            font-weight: normal;
        }

        table .billing td {
            text-align: center;
        }

        table .billing td h3 {
            color: #57B223;
            font-size: 1.2em;
            font-weight: normal;
            margin: 0 0 0 0;
        }

        table .no {
            color: #FFFFFF;
            font-size: 1.6em;
            background: #57B223;
            width: 3%;
        }

        #notices .notice {
            font-size: 1.2em;
        }

        footer {
            color: #777777;
            width: 100%;
            height: 30px;
            position: absolute;
            bottom: 0;
            border-top: 1px solid #AAAAAA;
            padding: 8px 0;
            text-align: center;
        }

        table.billing td {
            background-color: #fff;
        }

        table .billing td div#productd_to {
            text-align: left;
        }
    </style>
</head>
<body>
<header class="clearfix">
    <div class="billing">
        <div class="row">
            <div class="col-md-6">
                <div id="productd_to">
                    <small>Billed To:</small>
                    <h2 class="name">{{ ucwords($product->customer_name) }}</h2>
                    <div>{!! nl2br($product->client_address) !!}</div>
                </div>
            </div>
            <div class="col-md-6" id="company">
                <small>Generated By:</small>
                <h2 class="name">{{ ucwords($merchantBusiness->business->title) }}</h2>
                <div>@if(!is_null($merchantBusiness->business->address))
                        {!! nl2br($merchantBusiness->business->address) !!}
                    @endif</div>
                <div>@if(!is_null($merchantBusiness->business->phone))
                        {{ $merchantBusiness->business->phone }}
                    @endif</div>
            </div>
        </div>
    </div>
</header>
<main>

    <div id="details" class="clearfix">
        @php

            $digits_needed=5;

            $random_number=''; // set up a blank string

            $count=0;

            while ( $count < $digits_needed ) {
                $random_digit = mt_rand(0, 9);

                $random_number .= $random_digit;
                $count++;
            }

        @endphp
        <div id="product">
            <h1>product #IN{{ $random_number }}PD</h1>
            <div class="date">Date: {{ \Carbon\Carbon::today()->format('Y-m-d') }}</div>
        </div>

    </div>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th class="no">#</th>
            <th class="desc">Item</th>
            <th class="qty">Quantity</th>
            <th class="qty">Cost Per Item</th>
            <th class="qty">Discount(Amt)</th>
            <th class="unit">Price</th>
        </tr>
        </thead>
        <tbody>
        @php
            $arr['product_name'] = json_decode($product->product_name,true);
            $arr['product_price'] = json_decode($product->product_price,true);
            $arr['product_quantity'] = json_decode($product->product_quantity,true);
            $arr['product_discount'] = json_decode($product->product_discount,true);
            $arr['product_amount'] = json_decode($product->product_amount,true);
            $total = array_sum($arr['product_amount']);
            $j= count($arr['product_name']);
        @endphp
        <tr>
            <td>
                @for($i=0;$i<$j;$i++)
                    {{$i+1}} <br>
                @endfor
            </td>
            <td>
                @for($i=0;$i<$j;$i++)
                        <?php
                        $product_name = App\Models\Product::find($arr['product_name'][$i]);
                        ?>
                    {{$product_name->name ?? ''}} <br>
                @endfor
            </td>
            <td>
                @for($i=0;$i<$j;$i++)
                    {{$arr['product_quantity'][$i]}} <br>
                @endfor
            </td>
            <td>
                @for($i=0;$i<$j;$i++)
                    {{ $gymSettings->currency->acronym }} {{$arr['product_price'][$i]}} <br>
                @endfor
            </td>
            <td>
                @for($i=0;$i<$j;$i++)
                    {{$arr['product_discount'][$i]}} <br>
                @endfor
            </td>
            <td>
                @for($i=0;$i<$j;$i++)
                    {{ $gymSettings->currency->acronym }} {{$arr['product_amount'][$i]}} <br>
                @endfor
            </td>
        </tr>
        </tbody>
        <tfoot>
        <tr dontbreak="true">
            <td colspan="5">TOTAL</td>
            <td>{{ $gymSettings->currency->acronym }} {{ $total }}</td>
        </tr>
        </tfoot>
    </table>
</main>
</body>
</html>
