@extends('layouts.gym-merchant.gymbasic')

@section('CSS')
    <link rel="stylesheet" href="{{ asset("admin/global/plugins/datatables/datatables.min.css") }}">
    <link rel="stylesheet" href="{{ asset("admin/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.css") }}">
@stop

@section('content')
    <div class="container-fluid"      >
        <!-- BEGIN PAGE BREADCRUMBS -->
        <ul class="page-breadcrumb breadcrumb">
            <li>
                <a href="{{route('gym-admin.dashboard.index')}}">Home</a>
                <i class="fa fa-circle"></i>
            </li>
            <li>
                <span>Invoice</span>
            </li>
        </ul>
        <!-- END PAGE BREADCRUMBS -->
        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="page-content-inner">
            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="portlet light ">
                        <div class="portlet-title">
                            <div class="caption font-dark">
                                <i class="fa fa-file font-red"></i>
                                <span class="caption-subject font-red bold uppercase"> Invoices</span>
                            </div>
                            <div class="pull-right">
                                <div class="btn-group">
                                    <a href="{{route('gym-admin.gym-invoice.membershipIndex')}}" class="btn btn-success"> Membership Invoice
                                    </a>
                                    <a href="{{route('gym-admin.gym-invoice.productIndex')}}" class="btn btn-warning"> Product Invoice
                                    </a>
                                    <a href="{{route('gym-admin.gym-invoice.lockerIndex')}}" class="btn btn-info"> Locker Invoice
                                    </a>
                                    <a href="{{route('gym-admin.gym-invoice.create-invoice')}}" id="add_payment" class="btn dark"> Create <span class="hidden-xs">Invoice</span>
                                        <i class="fa fa-plus"></i>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="portlet-body">
                            <table class="table table-striped table-bordered table-hover order-column table-100" id="mem-payments">
                                <thead>
                                <tr>
                                    <th class="max-desktop" > Invoice # </th>
                                    <th class="desktop"> Client </th>
                                    <th class="desktop"> Date</th>
                                    <th class="desktop"> Total </th>
                                    <th class="desktop"> Generated By </th>
                                    <th class="desktop"> Items </th>
                                    <th class="desktop"> Actions</th>
                                </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                    <!-- END EXAMPLE TABLE PORTLET-->
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT INNER -->
    </div>

    {{--Model--}}

    <div class="modal fade bs-modal-md in" id="gymPaymemtModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-md" id="modal-data-application">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <span class="caption-subject font-red-sunglo bold uppercase" id="modelHeading"></span>
                </div>
                <div class="modal-body">
                    Loading...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn default" data-dismiss="modal">Close</button>
                    <button type="button" class="btn blue">Save changes</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>


    <div class="modal fade bs-modal-md in" id="receiptModal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-md" id="modal-data-application">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                    <span class="caption-subject font-red-sunglo bold uppercase" id="modelHeading"></span>
                </div>
                <div class="modal-body">
                    Loading...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn default" data-dismiss="modal">Close</button>
                </div>
            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

    {{--Model End--}}
@stop

@section('footer')
    <script src="{{ asset("admin/global/scripts/datatable.js") }}"></script>
    <script src="{{ asset("admin/pages/scripts/table-datatables-managed.js") }}"></script>
    <script src="{{ asset("admin/global/plugins/datatables/datatables.min.js") }}"></script>
    <script src="{{ asset("admin/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js") }}"></script>
    <script src="{{ asset("admin/global/plugins/bootbox/bootbox.min.js") }}"></script>
    <script>
        jQuery(document).ready(function() {
            load_dataTable();
        });
        function load_dataTable()
        {
            var table = $('#mem-payments');
            // begin first table
            table.dataTable({
                responsive: true,
                ajax: "{{route('gym-admin.gym-invoice.create',['type'=>'tax'])}}",
                bDestroy:true,
                columns: [
                    {data: 'invoice_number', name: 'invoice_number'},
                    {data: 'client_name', name: 'client'},
                    {data: 'invoice_date', name: 'date'},
                    {data: 'total', name: 'total'},
                    {data: 'generated_by', name: 'generated_by'},
                    {data: 'items_column', name: 'items'},
                    {data: 'action', name: 'action', orderable: false, searchable: false}
                ],
                pageLength: 25,
                lengthMenu: [
                    [25, 50, 75 , 100, -1],
                    ['25', '50','75' ,'100', 'All']
                ],
            });
        }

    </script>
    <script>
        $('#mem-payments').on('click','.remove-invoice',function(){
            var id = $(this).data('invoice-id');
            bootbox.confirm({
                message: "Do you want to delete this invoice?",
                buttons: {
                    confirm: {
                        label: "Yes",
                        className: "btn-primary"
                    }
                },
                callback: function(result){
                    if(result){

                        var url = "{{route('gym-admin.gym-invoice.destroy',':id')}}";
                        url = url.replace(':id',id);

                        $.easyAjax({
                            url: url,
                            type: "DELETE",
                            data: {id: id,_token: '{{ csrf_token() }}'},
                            success: function(){
                                load_dataTable();
                            }
                        });
                    }
                    else {
                        console.log('cancel');
                    }
                }
            })
        });
    </script>
@stop
