<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use App\Traits\LogUserDetailIdTrait;
/**
 * @method where(string $string,string $uuid )
 **/
class GymExpense extends Model
{
    use HasFactory,LogsActivity, LogUserDetailIdTrait ;

    protected $fillable = ['uuid','detail_id','item_name','category_id','purchase_date','supplier_id','price','bill','remarks'
    ,'payment_source','payment_status'];

    protected $table = 'expense_management';

    protected $dates = ['created_at'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getActivitylogOptions(): LogOptions
    {
        $user = auth()->guard('merchant')->user();
        $userId = $user ? $user->username : 'Unknown User';

        return LogOptions::defaults()
            ->logOnly([
                'detail_id','item_name','category_id','purchase_date','supplier_id','price','bill','remarks'
            ])
            ->logOnlyDirty()->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(function(string $eventName) use ($userId) {
                return "{$userId} has {$eventName} a GymExpense : {$this->item_name}";
            })
            ->useLogName('GymExpense');
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }

    public static function getExpenses($id) {
        $amount = GymExpense::where('detail_id',  $id)->sum('price');

        if(is_null($amount)) {
            return '0';
        }

        return $amount;
    }

    public function supplier(){
        return $this->belongsTo(GymSupplier::class,'supplier_id');
    }

    public function category(){
        return $this->belongsTo(ExpenseCategory::class,'category_id');
    }

    public static function getCurrentBalance($id) {
        return GymExpense::where('detail_id',$id)->sum('price');
    }

    public static function getDailySales($id) {
        return GymExpense::where('detail_id', $id)
            ->where('purchase_date', today())->sum('price');
    }

    public static function getWeeklySales($start,$end,$id) {
        return GymExpense::where('detail_id',$id)
            ->where('purchase_date', '>=', $start)->where('purchase_date', '<=', $end)
            ->sum('price');
    }

    public static function getAverageMonthlySales($month,$year,$id) {
        return GymExpense::where('detail_id', $id)
            ->whereMonth('purchase_date', $month)->whereYear('purchase_date', $year)->sum('price');
    }
}
