<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use App\Traits\LogUserDetailIdTrait;

/**
 * @OA\Schema(
 *     schema="Product",
 *     title="Product",
 *     description="Product Model",
 *     @OA\Property(property="id", type="integer", example=1),
 *     @OA\Property(property="tag", type="string", example="PROD123"),
 *     @OA\Property(property="name", type="string", example="Protein Powder"),
 *     @OA\Property(property="brand_name", type="string", example="HealthFit"),
 *     @OA\Property(property="quantity", type="integer", example=100),
 *     @OA\Property(property="price", type="integer", example=100),
 *     @OA\Property(property="quantity_expired", type="integer", example=10),
 *     @OA\Property(property="quantity_damaged", type="integer", example=5),
 *     @OA\Property(property="status", type="string", example="available"),
 *     @OA\Property(property="purchase_date", type="string", format="date", example="2023-07-01"),
 *     @OA\Property(property="expire_date", type="string", format="date", example="2024-07-01"),
 * )
 */
class Product extends Model
{
    use HasFactory, LogsActivity, LogUserDetailIdTrait, SoftDeletes;

    protected $fillable = [
        'id','branch_id','tag','name','brand_name','supplier','quantity','quantity_expired','quantity_damaged','status',
        'purchase_date', 'expire_date','price'
    ];

    protected $dates = ['purchase_date','expire_date'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getActivitylogOptions(): LogOptions
    {
        $user = auth()->guard('merchant')->user();
        $userId = $user ? $user->username : 'Unknown User';

        return LogOptions::defaults()
            ->logOnly([
              'branch_id','tag','name','brand_name','supplier','quantity','quantity_expired','quantity_damaged','status',
                'purchase_date', 'expire_date','price'
            ])
            ->logOnlyDirty()->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(function(string $eventName) use ($userId) {
                return " {$userId} has {$eventName} a Product : {$this->name}";
            })
            ->useLogName('Product');
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }

    public function suppliers() {
        return $this->belongsTo(GymSupplier::class,'supplier_id');
    }

    public function scopeExpireProductInDays($query,$businessId,$days,$limit = null){
        $start =  Carbon::today()->format('Y-m-d');
        $end =  Carbon::today()->addDays($days)->format('Y-m-d');
        return  $query->where('branch_id',$businessId)
            ->whereBetween('expire_date',[$start,$end])
            ->limit($limit)
            ->get();
    }

    public function quantityHistories()
    {
        return $this->hasMany(ProductQuantity::class);
    }

    public function addQuantity($quantity, $notes = null)
    {
        $previousQuantity = $this->quantity;
        $this->quantity += $quantity;
        $this->save();

        $this->quantityHistories()->create([
            'quantity' => $quantity,
            'type' => 'add',
            'previous_quantity' => $previousQuantity,
            'new_quantity' => $this->quantity,
            'notes' => $notes,
            'branch_id' => $this->branch_id
        ]);

        return $this;
    }

    public function removeQuantity($quantity, $notes = null)
    {
        if ($this->quantity < $quantity) {
            throw new \Exception('Insufficient quantity available');
        }

        $previousQuantity = $this->quantity;
        $this->quantity -= $quantity;
        $this->save();

        $this->quantityHistories()->create([
            'quantity' => $quantity,
            'type' => 'remove',
            'previous_quantity' => $previousQuantity,
            'new_quantity' => $this->quantity,
            'notes' => $notes,
            'branch_id' => $this->branch_id
        ]);

        return $this;
    }

    public function updateQuantity($newQuantity, $notes = null)
    {
        $previousQuantity = $this->quantity;
        $this->quantity = $newQuantity;
        $this->save();

        $this->quantityHistories()->create([
            'quantity' => abs($newQuantity - $previousQuantity),
            'type' => 'update',
            'previous_quantity' => $previousQuantity,
            'new_quantity' => $newQuantity,
            'notes' => $notes,
            'branch_id' => $this->branch_id
        ]);

        return $this;
    }
}
