<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
* @method static create(array $template)
 * @method where(string $string,string $uuid )
 **/
class Template extends Model
{
    use HasFactory;

    protected $fillable = ['uuid','name','type','message','status'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }

    public static function rules($action)
    {
        $rules = [
            'add'=>[
                'name' => 'required',
                'type' => 'required',
                'message' => 'required',
            ],
            'update'=>[
                'name' => 'required',
                'message' => 'required',
            ]
        ];
        return $rules[$action];
    }

    public static function businessTemplate($businessID,$id)
    {
        return Template::where('detail_id',$businessID)->where('uuid',$id)->first();
    }

    public static function businessTotalTemplate($businessID)
    {
        return Template::where('detail_id',$businessID)->count();
    }

    public static function businessTemplateMessage($businessID,$type)
    {
        return Template::where('detail_id',$businessID)->where('type',$type)->first();
    }

    public static function getTypes() : array {
        return [
          'registration',
          'payment',
          'due',
          'due_payment',
          'extend',
          'renew',
          'expire',
          'birthday',
          'anniversary','new_year','locker_due','locker_expire'
        ];
    }

    
    public static function getTags() : array {
        return [
          'mobile',
          'first_name',
          'middle_name',
          'last_name',
          'email',
          'membership',
          'expire_date',
          'due_date', //next_payment_date as due_date
          'birth_date',
          'anniversary_date',
          'company',
          'day','paid_amount','due_amount',
          'joining_date','locker_number'
        ];
    }

    public function renderSMS($msg,$data){
        //str_replace is case-sensitive and str_ireplace is not case-sensitive
        //preg_replace is not case-sensitive and return value if pattern matches

        preg_match_all('~{(.*?)}~s',$msg,$datas);
        foreach($datas[1] as $value){
            if(array_key_exists($value,$data)){
                $msg = preg_replace("/\b$value\b/u", $data[$value], $msg);
            }else{
                $msg = str_ireplace($value, '', $msg);
            }
        }
        return str_ireplace(["{", "}"], '', $msg);
    }
}
