<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use App\Traits\LogUserDetailIdTrait;

/**
 * @method where(string $string,string $uuid )
 **/

/**
 * @OA\Schema(
 *     schema="LockerReservation",
 *     title="Locker Reservation",
 *     description="Locker Reservation Model",
 *     @OA\Property(property="id", type="integer", example=123),
 *     @OA\Property(property="uuid", type="string", example="65c1eb979e66f"),
 *     @OA\Property(property="locker_id", type="integer", example=123),
 *     @OA\Property(
 *         property="locker",
 *         ref="#/components/schemas/Locker"
 *     ),
 *     @OA\Property(property="purchase_amount", type="number", format="float", example=100.50),
 *     @OA\Property(property="paid_amount", type="number", format="float", example=90.00),
 *     @OA\Property(property="discount", type="number", format="float", example=10.50),
 *     @OA\Property(property="purchase_date", type="string", format="date-time", example="2024-07-15T12:00:00Z"),
 *     @OA\Property(property="start_date", type="string", format="date-time", example="2024-07-15T12:00:00Z"),
 *     @OA\Property(property="next_payment_date", type="string", format="date", example="2024-08-15"),
 *     @OA\Property(property="end_date", type="string", format="date-time", example="2025-07-15T12:00:00Z"),
 *     @OA\Property(property="remarks", type="string", example="Reservation details"),
 *     @OA\Property(property="amount_to_be_paid", type="number", format="float", example=10.50),
 *     @OA\Property(property="payment_required", type="boolean", example=true),
 *     @OA\Property(property="status", type="integer", example=1),
 *     @OA\Property(property="deleted_at", type="string", format="date-time", example=null),
 *     @OA\Property(property="is_renew", type="boolean", example=false),
 * )
 */

class LockerReservation extends Model
{
    use HasFactory, SoftDeletes, LogsActivity, LogUserDetailIdTrait;

    protected $fillable = ['uuid','client_id','locker_id','assign_by','detail_id', 'purchase_amount','paid_amount',
        'discount','purchase_date','start_date','next_payment_date','end_date','remarks','amount_to_be_paid',
        'payment_required','status','deleted_at','is_renew'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getActivitylogOptions(): LogOptions
    {
        $user = null;

        if (auth()->guard('merchant')->check()) {
            $user = auth()->guard('merchant')->user();
        } elseif (auth()->guard('customer')->check()) {
            $user = auth()->guard('customer')->user();
        }elseif (auth()->guard('customer-api')->check()) {
            $user = auth()->guard('customer-api')->user();
        }

        $userId = $user ? $user->username : 'Unknown User';

        return LogOptions::defaults()
            ->logOnly([
                'client_id', 'locker_id', 'assign_by',
                'purchase_amount', 'paid_amount', 'discount',
                'purchase_date', 'start_date', 'next_payment_date',
                'end_date', 'remarks', 'amount_to_be_paid',
                'status', 'is_renew'
            ])
            ->logOnlyDirty()->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(function(string $eventName) use ($userId) {
                return " {$userId} has {$eventName} a LockerReservation for Client ID: {$this->client->username}";
            })
            ->useLogName('LockerReservation');
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }

    protected $casts = [
        'purchase_amount' => 'integer',
        'discount' => 'integer',
        'paid_amount' => 'integer',
    ];

    protected $dates = ['purchase_date', 'next_payment_date', 'start_date', 'end_date','deleted_at'];

    public static function rules($action)
    {
        $rules = [
            'add'=>[
                'client_id' => 'required',
                'locker_id' => 'required',
                'purchase_amount' => 'required|numeric',
                'amount_to_be_paid' => 'required|numeric',
                'discount' => 'nullable|numeric',
                'purchase_date' => 'required|date',
                'start_date' => 'required|date',
                'next_payment_date' => 'required|date',
                'remarks' => 'nullable',
                'payment_amount' => 'required|numeric',
                'payment_source' => 'exclude_if:payment_amount,0|required',
            ],
            'update'=>[
                'amount_to_be_paid' => 'required|numeric',
                'discount' => 'nullable|numeric',
                'start_date' => 'required|date',
                'next_payment_date' => 'required|date',
                'remarks' => 'nullable',
            ]
        ];
        return $rules[$action];
    }

    public static function getLockerExpire($lockerId,$start_date) {
        $locker = Locker::find($lockerId);
        $category = LockerCategory::find($locker->locker_category_id);
        $date = $category->duration;
        $type = $category->duration_type;
        $startDate = Carbon::createFromFormat('m/d/Y',$start_date);
        switch ($type){
            case ('month'):
                $expire = $startDate->addMonths($date);
                break;
            case ('year'):
                $expire =  $startDate->addYears($date);
                break;
            default:
                $expire =  $startDate->addDays($date);
                break;
        }
        return $expire;
    }

    public static function businessReservation($businessID){
        return LockerReservation::where('detail_id',$businessID)->get();
    }

    public static function countbusinessReservationStatus($businessID,$status){
        return LockerReservation::where('status',$status)->where('detail_id',$businessID)->count();
    }

    public function locker() {
        return $this->belongsTo(Locker::class);
    }

    public function client() {
        return $this->belongsTo(GymClient::class);
    }

    public function scopeExpireReservationInDays($query,$businessId,$days,$limit = null){
        $start =  Carbon::today()->format('Y-m-d');
        $end =  Carbon::today()->addDays($days)->format('Y-m-d');
        return  $query->where('detail_id',$businessId)
            ->whereBetween('end_date',[$start,$end])
            ->limit($limit)
            ->get();
    }

    public function scopeDueLockerPayment($query,$businessId,$limit = null){
        return  $query->where('detail_id',$businessId)->where('status','active')->where('payment_required','yes')
            ->limit($limit)->get();
    }

    public static function clientReservation($businessId,$clientId,$lockerId) {
        return LockerReservation::where('detail_id',$businessId)->where('client_id',$clientId)
            ->where('locker_id',$lockerId)->where('payment_required','yes')->latest()->get();
    }

}
