<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class BodyMeasurement extends Model
{
    use HasFactory,SoftDeletes;

    protected $fillable = ['uuid','client_id','added_by','entry_date','weight','height_feet','height_inches','fat',
        'fore_arms','neck','shoulder', 'chest','waist', 'hip','thigh','calves','arms'];

    protected $dates = ['entry_date'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            foreach($apps->toArray() as $key=>$value){
                $apps->{$key} = is_null($value) ? 0 : $value;
            }
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public static function rules($action)
    {
        $rules = [
            'add'=>[
                'weight' => 'required',
                'height_feet' => 'required',
                'height_inches' => 'required',
                'chest' => 'required',
                'fat' => 'required',
                'waist' => 'required',
                'hip' => 'required',
                'arms' => 'required',
                'fore_arms' => 'required',
                'shoulder' => 'required',
                'calves' => 'required',
                'neck' => 'required',
                'thigh' => 'required',
            ]
        ];
        return $rules[$action];
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }

    public function client()
    {
        return $this->belongsTo(GymClient::class);
    }

    public static function getMeasurementData($clientId,$take = null,$skip = null,$start = null,$end = null){
        $data = BodyMeasurement::where('client_id',$clientId)
            ->when($start != null,function($query) use ($start,$end){
                return $query->whereDate('entry_date',$start)->orWhereDate('entry_date',$end);
            })
            ->when($skip != null,function($q) use ($skip){
                return $q->where('id','!=',$skip);
            })
            ->orderBy('entry_date','desc')->latest()->take($take);
        return $data;
    }

    public static function clientProgressTracker($clientId,$start = null,$end = null){
        $data = [
            'height'=>0,'weight'=>0,'fat'=>0,'neck'=>0,'fore_arms'=>0,'shoulder'=>0,
            'waist'=>0,'hip'=>0,'thigh'=>0,'arms'=>0,'chest'=>0,'calves'=>0
        ];
        $measurements = BodyMeasurement::where('client_id',$clientId)
                ->where(function($query) use ($start,$end){
                    $query->whereDate('entry_date',$start)->orWhereDate('entry_date',$end);
                })
                ->orderBy('entry_date','desc')->latest()->take(2)->get();
            foreach($data as $key => $val) { //first->new,last->old
                if($key == 'height'){
                    $height_old = $measurements->last()->height_feet + $measurements->last()->height_inches * 0.0833333 ;
                    $height_new = $measurements->first()->height_feet + $measurements->first()->height_inches * 0.0833333 ;
                    $delta = $height_new - $height_old;
                    $data['height'] = round($delta/ $height_new *100,2);
                }else{
                    $delta = $measurements->first()->{$key} - $measurements->last()->{$key};
                }
                if($delta != 0 && $key !== 'height' && $measurements->first()->{$key} != 0) {
                    $data[$key] = round($delta / $measurements->first()->{$key} * 100 , 2);
                }
            }
            return $data;
    }

}
