<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use App\Traits\LogUserDetailIdTrait;

/**
 * @OA\Schema(
 *     schema="ClassSchedule",
 *     title="ClassSchedule",
 *     description="ClassSchedule Model",
 *     @OA\Property(property="id", type="integer", example=5),
 *     @OA\Property(property="className", type="string", example="Yoga"),
 *     @OA\Property(property="trainer", type="string", example="John Doe"),
 *     @OA\Property(property="days", type="array", @OA\Items(type="string", example="sunday")),
 *     @OA\Property(property="startTime", type="string", format="time", example="06:00:00"),
 *     @OA\Property(property="endTime", type="string", format="time", example="07:00:00"),
 * )
 */
class ClassSchedule extends Model
{
    use HasFactory, SoftDeletes, LogsActivity, LogUserDetailIdTrait;

    protected $table = "class_schedules";

    protected $fillable = [
        'id','days','startTime','endTime','uuid','has_client','class_id','trainer_id','detail_id'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getActivitylogOptions(): LogOptions
    {
        $user = auth()->guard('merchant')->user();
        $userId = $user ? $user->username : 'Unknown User';

        return LogOptions::defaults()
            ->logOnly([
              'days','startTime','endTime','uuid','has_client','class_id','trainer_id','detail_id'
            ])
            ->logOnlyDirty()->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(function(string $eventName) use ($userId) {
                return "{$userId} has {$eventName} a ClassSchedule of : {$this->classes->class_name}";
            })
            ->useLogName('ClassSchedule');
    }

    public static function rules($action)
    {
        $rules = [
            'add'=>[
                'trainer' => 'required',
                'class' => 'required',
                'startTime' => 'required',
                'endTime' => 'required',
                'assign_to' => 'required',
                'days' => 'required',
                'client' => 'required_if:assign_to,true',
            ]
        ];
        return $rules[$action];
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }

    public function clients(){
        return $this->belongsToMany(GymClient::class,'gym_client_class_schedule','class_schedule_id','client_id');
    }

    public function classes()
    {
        return $this->belongsTo(Classes::class,'class_id');
    }

    public function trainers()
    {
        return $this->belongsTo(Trainers::class,'trainer_id');
    }
}
