<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Auth\Authenticatable as Authenticatable;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use App\Traits\LogUserDetailIdTrait;


/**
 * @OA\Schema(
 *     schema="GymClient",
 *     title="Gym Client",
 *     description="Gym Client Model",
 *     @OA\Property(property="id", type="integer", example=6393),
 *     @OA\Property(property="first_name", type="string", example="John"),
 *     @OA\Property(property="middle_name", type="string", example="Doe"),
 *     @OA\Property(property="last_name", type="string", example="Smith"),
 *     @OA\Property(property="dob", type="string", format="date-time", example=null),
 *     @OA\Property(property="gender", type="string", enum={"male", "female", "other"}, example="male"),
 *     @OA\Property(property="email", type="string", format="email", example="customer@example.com"),
 *     @OA\Property(property="address", type="string", example=null),
 *     @OA\Property(property="mobile", type="string", example="1234567890"),
 *     @OA\Property(property="emergency_contact", type="string", example="1234567890"),
 *     @OA\Property(property="blood_group", type="string", example="a+"),
 *     @OA\Property(property="is_gym_experience", type="integer", example=0),
 *     @OA\Property(property="joining_date", type="string", format="date-time", example="2024-02-06T00:00:00.000000Z"),
 *     @OA\Property(property="weight", type="integer", example=0),
 *     @OA\Property(property="fat", type="integer", example=null),
 *     @OA\Property(property="height_feet", type="integer", example=0),
 *     @OA\Property(property="height_inches", type="integer", example=0),
 *     @OA\Property(property="chest", type="integer", example=null),
 *     @OA\Property(property="waist", type="integer", example=null),
 *     @OA\Property(property="arms", type="integer", example=null),
 *     @OA\Property(property="image", type="string", example="/uploads/profile_pic/master/image.jpeg"),
 *     @OA\Property(property="client_source", type="string", example="huntplex"),
 *     @OA\Property(property="marital_status", type="string", enum={"single", "married", "divorced", "widowed", "other"}, example="no"),
 *     @OA\Property(property="anniversary", type="string", format="date", example=null),
 *     @OA\Property(property="occupation", type="string", example="Other"),
 *     @OA\Property(property="occupation_details", type="string", example=null),
 *     @OA\Property(property="redeem_points", type="integer", example=0),
 *     @OA\Property(property="referred_client_id", type="integer", example=6379),
 *     @OA\Property(property="status", type="integer", example=1),
 *     @OA\Property(property="remarks", type="string", example=null),
 *     @OA\Property(property="device_name", type="string", example="device"),
 * )
 */

class GymClient extends Model implements AuthenticatableContract, CanResetPasswordContract
{
    use HasFactory,HasApiTokens, SoftDeletes;

    use Authenticatable, CanResetPassword, Notifiable, LogsActivity, LogUserDetailIdTrait;
    protected $dates = ['joining_date','dob','anniversary'];
    protected $table = 'gym_clients';
    protected $guarded = ['id'];
    public static $MAX_CLIENTS = 100;
    protected $guard = "customer";

    protected static $recordEvents = ['deleted','created'];

    protected $fillable = ['uuid','api_token','username','first_name','middle_name','last_name','dob','gender','email','password','address','mobile','emergency_contact',
        'blood_group','is_gym_experience','joining_date','weight','fat','height_feet','height_inches','chest',
        'waist','arms','image','client_source','marital_status','anniversary','occupation','occupation_details','redeem_points',
        'referred_client_id','status','card','remarks','is_device_deleted','is_denied','is_expired','device_name','is_client'];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getActivitylogOptions(): LogOptions
    {
        $user = null;

        if (auth()->guard('merchant')->check()) {
            $user = auth()->guard('merchant')->user();
        } elseif (auth()->guard('customer')->check()) {
            $user = auth()->guard('customer')->user();
        }elseif (auth()->guard('customer-api')->check()) {
            $user = auth()->guard('customer-api')->user();
        }
        $userId = $user ? $user->username : 'Unknown User';

        return LogOptions::defaults()
            ->logOnly([
               'first_name','middle_name','last_name','email','password','mobile','emergency_contact','address',
               'joining_date','referred_client_id','status','is_device_deleted','is_denied','is_expired','device_name'
            ])
            ->logOnlyDirty()->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(function(string $eventName) use ($userId) {
                return "{$userId} has {$eventName} a GymClient: {$this->email}";
            })
            ->useLogName('GymClient');
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }

    public static function rules($action, $id=null, $businessID) {
        $rules = [
            'general' => [
                'first_name' => 'required|alpha_spaces',
                'last_name' => 'required|alpha_spaces',
                'gender' => 'required',
                'email' => 'required|email|unique:gym_clients,email,deleted_at,NULL,'.$id.',id,detail_id,email'.$businessID,
                'dob' => 'required',
                'mobile' => 'required|unique:gym_clients,mobile,'.$id.',id,detail_id,'.$businessID,
                'emergency_contact' => 'required',
                'blood_group' => 'required',
                'age' => 'numeric',
                'marital_status' => 'required',
                'height_inches' => 'numeric',
                'height_feet' => 'numeric',
                'weight' => 'numeric',
                'fat' => 'numeric',
                'chest' => 'numeric',
                'waist' => 'numeric',
                'arms' => 'numeric',
            ],
            'file' => [
                'file' => ''
            ]
        ];
        return $rules[$action];
    }

    public function scopeActive($query){
        $query->where('status',1);
    }

    public static function GetClients($businessId) {
        return GymClient::join('business_customers', 'business_customers.customer_id', '=', 'gym_clients.id')
            ->where('business_customers.detail_id', '=', $businessId)
            ->where('gym_clients.is_client','yes')
            ->select('gym_clients.id', 'gym_clients.first_name', 'gym_clients.middle_name','gym_clients.email','gym_clients.mobile','gym_clients.last_name','gym_clients.image','business_customers.customer_id',
                'gym_clients.joining_date', 'gym_clients.occupation','gym_clients.emergency_contact','gym_clients.dob','gym_clients.referred_client_id','gym_clients.redeem_points','gym_clients.status','gym_clients.card',
                'gym_clients.is_device_deleted','gym_clients.is_denied','gym_clients.is_expired','gym_clients.username')
            ;
    }

    public static function GetEmployeeFromClients($businessId) {
        return GymClient::join('business_customers', 'business_customers.customer_id', '=', 'gym_clients.id')
            ->where('business_customers.detail_id', '=', $businessId)
            ->where('gym_clients.is_client','no')
            ->select('gym_clients.id', 'gym_clients.first_name', 'gym_clients.middle_name','gym_clients.email','gym_clients.mobile','gym_clients.last_name','gym_clients.image','business_customers.customer_id',
                'gym_clients.joining_date', 'gym_clients.occupation','gym_clients.emergency_contact','gym_clients.dob','gym_clients.referred_client_id','gym_clients.redeem_points','gym_clients.status','gym_clients.card',
                'gym_clients.is_device_deleted','gym_clients.is_denied','gym_clients.is_expired')->distinct()
            ;
    }

    public static function findBusinessClient($businessId,$clientId) {
        return GymClient::join('business_customers', 'business_customers.customer_id', '=', 'gym_clients.id')
            ->select('gym_clients.*','business_customers.customer_id')
            ->where('business_customers.detail_id', $businessId)->where('gym_clients.is_client','yes')
            ->where('gym_clients.id', $clientId)->get();
    }

    //client active membership
    public static function countActiveClient($businessId)
    {
        return GymClient::getActiveClient($businessId)->count();
    }

    public static function getActiveClient($businessId)
    {
        return GymClient::join('business_customers', 'business_customers.customer_id', '=', 'gym_clients.id')
           ->whereHas('subscriptions', function (Builder $query) {
                $query->latest()->whereDate('expires_on', '>', today()->format('Y-m-d'));
            })
             ->select('gym_clients.id', 'gym_clients.first_name', 'gym_clients.middle_name','gym_clients.last_name','business_customers.customer_id','gym_clients.card','gym_clients.mobile')
             ->where('gym_clients.is_client','yes')
             ->where('business_customers.detail_id', $businessId)
            ->active()->distinct()->get();
    }

    //get active user and user who are not enroll in device
    public static function getActiveClientWithoutShifts($businessId)
    {
        return GymClient::join('business_customers', 'business_customers.customer_id', '=', 'gym_clients.id')
           ->whereHas('subscriptions', function (Builder $query) {
                $query->latest()->whereDate('expires_on', '>', today()->format('Y-m-d'));
            })
            ->doesntHave('shifts')
             ->select('gym_clients.id', 'gym_clients.first_name', 'gym_clients.middle_name','gym_clients.last_name','business_customers.customer_id','gym_clients.card')
             ->where('gym_clients.is_client','yes')
             ->where('business_customers.detail_id', $businessId)
            ->active()->distinct()->take(10)->get();
    }

    public static function getActiveClientWithCardIsNull($businessId)
    {
        return GymClient::join('business_customers', 'business_customers.customer_id', '=', 'gym_clients.id')
           ->whereHas('subscriptions', function (Builder $query) {
                $query->latest()->whereDate('expires_on', '>', today()->format('Y-m-d'));
            })
            ->has('shifts')
            ->select('gym_clients.id', 'gym_clients.first_name', 'gym_clients.middle_name','gym_clients.last_name','business_customers.customer_id','gym_clients.card')
            ->where('gym_clients.is_client','yes')
            ->where('business_customers.detail_id', $businessId)
            ->whereNull('card')
            ->active()->distinct()->take(10)->get();
    }

    public static function monthlyClients($businessId, $month) {
        return GymClient::join('business_customers', 'business_customers.customer_id', '=', 'gym_clients.id')
            ->whereMonth('gym_clients.joining_date', $month)->whereYear('gym_clients.joining_date', now()->year)
            ->where('gym_clients.is_client','yes')
            ->where('business_customers.detail_id', '=', $businessId)
            ->count();
    }

    public function trainingPlan()
    {
        return $this->hasOne(TrainingPlan::class,'client_id','id');
    }

    public function syncLog()
    {
        return $this->hasOne(SyncLog::class,'client_id','id')->latest();
    }

    public function subscriptions()
    {
        return $this->hasMany(GymPurchase::class,'client_id','id');
    }

    public function product_sells()
    {
        return $this->hasMany(ProductSales::class,'client_id','id');
    }

    public function memberships()
    {
        return $this->belongsToMany(GymMembership::class,'gym_client_purchases','client_id','membership_id');
    }

    public function activeMembership(){
        return $this->hasOne(GymPurchase::class,'client_id','id')
            ->latestOfMany('expires_on')->whereNotNull('expires_on');
    }

    public function activeLockerReservation(){
        return $this->hasOne(LockerReservation::class,'client_id','id')
            ->latestOfMany('end_date')->whereNotNull('end_date');
    }

    public function devices()
    {
        return $this->belongsToMany(Device::class,'device_gym_clients','client_id','device_id')
                    ->withPivot(['is_denied', 'is_device_deleted','is_expired']);
    }

    public function shifts()
    {
        return $this->belongsToMany(Shift::class,'gym_client_shift','client_id','shift_id');
    }

    public function latestDeviceClients()
    {
        return $this->devices->first();
    }

    public function getFullNameAttribute()
    {
        return ucfirst($this->first_name ). ' '. ucfirst($this->middle_name) .' '. ucfirst($this->last_name);
    }

    public function message_thread()
    {
        return $this->hasMany(MessageThread::class,'customer_id','id');
    }

    public function bodyMeasurement()
    {
        return $this->hasMany(BodyMeasurement::class,'client_id','id');
    }

    public function latestMeasurement()
    {
        return $this->hasOne(BodyMeasurement::class,'client_id','id')
            ->latestOfMany();
    }

    public function scopeSubscriptionData($query)
    {
        $subscribe = $this->subscriptions()->first();
        $today = Carbon::now()->format('Y-m-d');
        if($subscribe == null ){
            $data = 'No Subscription';
        }else{
            if($subscribe->expires_on >= $today){
                $data = $this->getFullnameAttribute().','.$this->email.",".$subscribe->membership->title;
            }else{
                $data = "Expire Subscription";
            }
        }
        return $data;
    }

    public function extend_subscription() {
        return $this->hasMany(GymMembershipExtend::class);
    }

    public function reservations() {
        return $this->hasMany(LockerReservation::class,'client_id');
    }

    public function reviews() {
        return $this->hasMany(Review::class,'client_id');
    }

    public static function todayClientBirthday($businessId){
        $today = Carbon::now()->format('d');
        $month = Carbon::now()->format('m');

        return GymClient::has('subscriptions')
            ->join('business_customers', 'business_customers.customer_id', '=', 'gym_clients.id')
            ->where('business_customers.detail_id', $businessId)
            ->where('gym_clients.is_client','yes')
            ->whereMonth('dob',$month)
            ->whereDay('dob',$today)

            ->select('gym_clients.id as id','first_name','middle_name','last_name')->get();
    }

    public static function todayClientAnniversary($businessId){
        $today = Carbon::now()->format('d');
        return GymClient::has('subscriptions')
            ->join('business_customers', 'business_customers.customer_id', '=', 'gym_clients.id')
            ->where('business_customers.detail_id', $businessId)
            ->where('gym_clients.is_client','yes')
            ->whereDay('anniversary',$today)
            ->select('gym_clients.id as id','first_name','middle_name','last_name')->get();
    }

    public function classSchedules()
    {
        return $this->belongsToMany(ClassSchedule::class,'gym_client_class_schedule','client_id','class_schedule_id');
    }

    public function referred_by()
    {
        return $this->belongsTo(GymClient::class,'referred_client_id');
    }

    public static function getClientReferredLists($businessId,$clientId)
    {
        return GymClient::GetClients($businessId)->where('referred_client_id',$clientId);
    }

    public function clientDeviceSync(){
        return $this->hasOne(SyncLog::class,'client_id')->where('synced',1);
    }
}
