<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use App\Traits\LogUserDetailIdTrait;

class GymMembershipFreeze extends Model
{
    use HasFactory, LogsActivity, LogUserDetailIdTrait, SoftDeletes;
    protected $table = 'gym_membership_freeze';

    protected $fillable = ['uuid','is_frozen','client_id','purchase_id','added_by','detail_id','reasons','days','start_date','end_date',];

    protected $dates = ['start_date','end_date'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getActivitylogOptions(): LogOptions
    {
        $user = null;

        if (auth()->guard('merchant')->check()) {
            $user = auth()->guard('merchant')->user();
        } elseif (auth()->guard('customer')->check()) {
            $user = auth()->guard('customer')->user();
        }

        $userId = $user ? $user->username : 'Unknown User';

        return LogOptions::defaults()
            ->logOnly([
              'is_frozen','client_id','purchase_id','added_by','detail_id','reasons','days','start_date','end_date',
            ])
            ->logOnlyDirty()->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(function(string $eventName) use ($userId) {
                return "{$userId} has {$eventName} a GymMembershipFreeze for Client : {$this->client->username}";
            })
            ->useLogName('GymMembershipFreeze');
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }

    public function client() {
        return $this->belongsTo(GymClient::class,'client_id');
    }

    public function purchase() {
        return $this->belongsTo(GymPurchase::class,'purchase_id');
    }

    public function addedBy() {
        return $this->belongsTo(Merchant::class,'added_by');
    }
}