<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use App\Traits\LogUserDetailIdTrait;

class GymMembershipExtend extends Model
{
    use HasFactory,LogsActivity, SoftDeletes;

    protected $table = 'gym_membership_extends';

    protected $fillable = ['uuid','client_id','purchase_id','detail_id','reasons','days','extend_from','extend_to'];

    protected $dates = ['extend_from','extend_to'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getActivitylogOptions(): LogOptions
    {
        $user = null;

        if (auth()->guard('merchant')->check()) {
            $user = auth()->guard('merchant')->user();
        } elseif (auth()->guard('customer')->check()) {
            $user = auth()->guard('customer')->user();
        }

        $userId = $user ? $user->username : 'Unknown User';

        return LogOptions::defaults()
            ->logOnly([
               'client_id','purchase_id','detail_id','reasons','days','extend_from','extend_to'
            ])
            ->logOnlyDirty()->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(function(string $eventName) use ($userId) {
                return "{$userId} has {$eventName} a GymMembershipExtend for Client : {$this->client->username}";
            })
            ->useLogName('GymMembershipExtend');
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public function client() {
        return $this->belongsTo(GymClient::class,'client_id');
    }

    public function purchase() {
        return $this->belongsTo(GymPurchase::class,'purchase_id');
    }

    public function extendBy() {
        return $this->belongsTo(Merchant::class,'extend_by');
    }

}