<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class GymTutorial extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'gym_tutorial';

    protected $fillable = ['title', 'is_default','description', 'iframe_code','status', 'detail_id', 'type', 'image'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }
    public static function rules($action)
    {
        $rules = [
            'add'=>[
                'title' => 'required|string|max:255',
                'type' => 'required|in:text,video,audio,image',
                'description' => 'nullable|string',
                'iframe_code' => 'nullable|string',
                'image' => 'nullable|image',
            ]
        ];
        return $rules[$action];
    }

}