<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use App\Traits\LogUserDetailIdTrait;

class IncomeCategory extends Model
{
    use HasFactory, LogsActivity, LogUserDetailIdTrait;

    protected $fillable = ['uuid','detail_id','title'];

    protected $appends = ['total_income'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getActivitylogOptions(): LogOptions
    {
        $user = auth()->guard('merchant')->user();
        $userId = $user ? $user->username : 'Unknown User';

        return LogOptions::defaults()
            ->logOnly([
              'detail_id','title'
            ])
            ->logOnlyDirty()->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(function(string $eventName) use ($userId) {
                return " {$userId} has {$eventName} a IncomeCategory : {$this->title}";
            })
            ->useLogName('IncomeCategory');
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }

    public function incomes(){
        return $this->hasMany(Income::class,'category_id');
    }

    public function getTotalIncomeAttribute(){
        return $this->hasMany(Income::class,'category_id')->sum('price');
    }
}
