<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use App\Traits\LogUserDetailIdTrait;

class Income extends Model
{
    use HasFactory, LogsActivity, LogUserDetailIdTrait;

    protected $fillable = ['uuid','detail_id','supplier_id','category_id','purchase_date','price','bill','remarks',
        'payment_source'];

    protected $dates = ['purchase_date'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getActivitylogOptions(): LogOptions
    {
        $user = auth()->guard('merchant')->user();
        $userId = $user ? $user->username : 'Unknown User';
        return LogOptions::defaults()
            ->logOnly([
               'detail_id','supplier_id','category_id','purchase_date','price','bill','remarks'
            ])
            ->logOnlyDirty()->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(function(string $eventName) use ($userId) {
                return " {$userId} has {$eventName} a Income : {$this->category->title}";
            })
            ->useLogName('Income');
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }

    public function category(){
        return $this->belongsTo(IncomeCategory::class,'category_id');
    }

    public function supplier(){
        return $this->belongsTo(GymSupplier::class,'supplier_id');
    }

    public static function getCurrentBalance($id) {
        return Income::where('detail_id',$id)->sum('price');
    }

    public static function getDailySales($id) {
        return Income::where('detail_id', $id)
            ->where('purchase_date', today())->sum('price');
    }

    public static function getWeeklySales($start,$end,$id) {
        return Income::where('detail_id',$id)
            ->where('purchase_date', '>=', $start)->where('purchase_date', '<=', $end)
            ->sum('price');
    }

    public static function getAverageMonthlySales($month,$year,$id) {
        return Income::where('detail_id', $id)
            ->whereMonth('purchase_date', $month)->whereYear('purchase_date', $year)->sum('price');
    }

}
