<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use App\Traits\LogUserDetailIdTrait;

/**
 * @method where(string $string,string $uuid )
 **/

/**
 * @OA\Schema(
 *     schema="LockerPayment",
 *     title="Locker Payment",
 *     description="Locker Payment Model",
 *     @OA\Property(property="id", type="integer", example=123),
 *     @OA\Property(property="uuid", type="string", example="65c1eb979e66f"),
 *     @OA\Property(
 *         property="reservation",
 *         ref="#/components/schemas/LockerReservation"
 *     ),
 *     @OA\Property(property="payment_id", type="integer", example=987),
 *     @OA\Property(property="payment_amount", type="number", format="float", example=100.50),
 *     @OA\Property(property="payment_date", type="string", format="date-time", example="2024-07-15T12:00:00Z"),
 *     @OA\Property(property="payment_source", type="string", example="Credit Card"),
 *     @OA\Property(property="remarks", type="string", example="Payment details"),
 * )
 */


class LockerPayment extends Model
{
    use HasFactory , SoftDeletes, LogsActivity, LogUserDetailIdTrait;

    protected $fillable = ['uuid','detail_id','reservation_id','client_id','payment_id','payment_amount','payment_date','payment_source','remarks'];

    protected $dates = ['payment_date','deleted_at'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($payment){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $payment->payment_id = 'P-'.rand(1000,9999);
            $payment->uuid = $uid;
        });
    }

    public function getActivitylogOptions(): LogOptions
    {
        $user = null;

        if (auth()->guard('merchant')->check()) {
            $user = auth()->guard('merchant')->user();
        } elseif (auth()->guard('customer')->check()) {
            $user = auth()->guard('customer')->user();
        }elseif (auth()->guard('customer-api')->check()) {
            $user = auth()->guard('customer-api')->user();
        }

        $userId = $user ? $user->username : 'Unknown User';
        return LogOptions::defaults()
            ->logOnly(['reservation_id','client_id','payment_id','payment_amount','payment_date','payment_source','remarks'])
            ->logOnlyDirty()->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(function(string $eventName) use ($userId) {
                return " {$userId} has {$eventName} a LockerPayment for Client: {$this->client->username}";
            })
            ->useLogName('LockerPayment');
    }

    public static function rules($action) {
        $rules = [
            'add' => [
                'payment_amount' => 'required|numeric|min:1',
                'payment_source' => 'required',
                'payment_date' => 'required',
                'payment_required' => 'required',
            ],
            'ajax_add' => [
                'payment_amount' => 'required|numeric|min:1',
                'payment_source' => 'required',
                'payment_date' => 'required'
            ]
        ];
        return $rules[$action];
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }

    public function client() {
        return $this->belongsTo(GymClient::class, 'client_id');
    }

    public function reservation() {
        return $this->belongsTo(LockerReservation::class, 'reservation_id');
    }

    public static function getCurrentBalance($id) {
        return LockerPayment::has('reservation')->where('detail_id',$id)->sum('payment_amount');
    }

    public static function getDailySales($id) {
        return LockerPayment::has('reservation')->where('payment_date', today())->where('detail_id',$id)->sum('payment_amount');
    }

    public static function getWeeklySales($start,$end,$id) {
        return LockerPayment::has('reservation')->where('detail_id',$id)
            ->where('payment_date', '>=', $start)->where('payment_date', '<=', $end)
            ->sum('payment_amount');
    }

    public static function getAverageMonthlySales($month,$year,$id) {
        return LockerPayment::has('reservation')->where('detail_id', $id)
            ->whereMonth('payment_date', $month)->whereYear('payment_date', $year)->sum('payment_amount');
    }
}
