<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use App\Traits\LogUserDetailIdTrait;

/**
* @method where(string $string,string $uuid )
 **/

/**
 * @OA\Schema(
 *     schema="LockerCategory",
 *     title="LockerCategory",
 *     description="LockerCategory Model",
 *     @OA\Property(property="id", type="integer", example=123),
 *     @OA\Property(property="uuid", type="string", example="65c1eb979e66f"),
 *     @OA\Property(property="title", type="string", example="Small Locker"),
 *     @OA\Property(property="price", type="number", format="float", example=50.00),
 *     @OA\Property(property="duration", type="integer", example=1),
 *     @OA\Property(property="duration_type", type="string", enum={"day", "week", "month", "year"}, example="month"),
 *     @OA\Property(property="details", type="string", example="Locker category details"),
 *     @OA\Property(property="type", type="string", enum={"small", "medium","large"}, example="small"),
 *     @OA\Property(property="three_month_price", type="number", format="float", example=120.00),
 *     @OA\Property(property="six_month_price", type="number", format="float", example=200.00),
 *     @OA\Property(property="one_year_price", type="number", format="float", example=350.00),
 * )
 */

class LockerCategory extends Model
{
    use HasFactory, LogsActivity, LogUserDetailIdTrait;

    protected $fillable = ['uuid','title','price','duration','duration_type','details','type','detail_id',
        'three_month_price','one_year_price','six_month_price'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getActivitylogOptions(): LogOptions
    {
        $user = auth()->guard('merchant')->user();
        $userId = $user ? $user->username : 'Unknown User';

        return LogOptions::defaults()
            ->logOnly(['title','price','duration','duration_type','details','type','detail_id',
                'three_month_price','one_year_price','six_month_price'])
            ->logOnlyDirty()->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(function(string $eventName) use ($userId) {
                return " {$userId} has {$eventName} a LockerCategory : {$this->title}";
            })
            ->useLogName('LockerCategory');
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }
    public static function rules($action)
    {
        $rules = [
            'add'=>[
                'title' => 'required',
                'price' => 'required',
                'type' => 'required',
                'details' => 'nullable',
            ]
        ];
        return $rules[$action];
    }

    public function lockers()
    {
        return $this->hasMany(Locker::class,'locker_category_id','id');
    }

    public function reservations()
    {
        return $this->hasManyThrough(LockerReservation::class,Locker::class,'locker_category_id','locker_id',);
    }

    public static function businessLockerCategory($businessID)
    {
        return LockerCategory::where('detail_id',$businessID)->get();
    }

    public static function businessLockerCategoryDetail($businessID,$id)
    {
        return LockerCategory::where('uuid',$id)->where('detail_id',$businessID)->first();
    }

    public static function countStatus($businessID,$categoryId,$status) {
        return Locker::where('status',$status)->where('locker_category_id',$categoryId)
            ->where('detail_id','=',$businessID)->count();
    }
}
