<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\Activitylog\Traits\LogsActivity;
use Spatie\Activitylog\LogOptions;
use App\Traits\LogUserDetailIdTrait;

/**
 * @method where(string $string,string $uuid )
 **/

/**
 * @OA\Schema(
 *     schema="Locker",
 *     title="Locker",
 *     description="Locker Model",
 *     @OA\Property(property="id", type="integer", example=123),
 *     @OA\Property(property="uuid", type="string", example="65c1eb979e66f"),
 *     @OA\Property(property="locker_num", type="string", example="A001"),
 *     @OA\Property(property="status", type="string", example="available"),
 *     @OA\Property(property="details", type="string", example="Locker details"),
 *     @OA\Property(
 *         property="locker_category",
 *         ref="#/components/schemas/LockerCategory"
 *     ),
 * )
 */


class Locker extends Model
{
    use HasFactory, LogsActivity, LogUserDetailIdTrait, SoftDeletes;

    protected $fillable = ['uuid','locker_num','status','details','detail_id','locker_category_id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getActivitylogOptions(): LogOptions
    {
        $user = null;

        if (auth()->guard('merchant')->check()) {
            $user = auth()->guard('merchant')->user();
        } elseif (auth()->guard('customer')->check()) {
            $user = auth()->guard('customer')->user();
        }

        $userId = $user ? $user->username : 'Unknown User';

        return LogOptions::defaults()
            ->logOnly(['locker_num','status','locker_category_id','details'])
            ->logOnlyDirty()->dontSubmitEmptyLogs()
            ->setDescriptionForEvent(function(string $eventName) use ($userId) {
                return " {$userId} has {$eventName} a Locker: {$this->locker_num}";
            })
            ->useLogName('Locker');
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }

    public static function rules($action)
    {
        $rules = [
            'add'=>[
                'locker_num' => 'required',
                'status' => 'required',
                'details' => 'nullable',
            ]
        ];
        return $rules[$action];
    }

    public function scopeActive($query,$businessID) {
        return $query->where('status','available')->where('detail_id',$businessID);
    }

    public static function businessLockers($businessID)
    {
        return Locker::where('detail_id',$businessID)->get();
    }

    public static function businessLockerDetail($businessID,$id)
    {
        return Locker::where('uuid',$id)->where('detail_id',$businessID)->first();
    }

    public function lockerCategory() {
        return $this->belongsTo(LockerCategory::class,'locker_category_id');
    }

    public function reservations() {
        return $this->hasMany(LockerReservation::class,'locker_id');
    }

    public function payments()
    {
        return $this->hasManyThrough(LockerPayment::class, LockerReservation::class,
            'locker_id','reservation_id','id');
    }

    public function getStatusType($value){
        if ($value == 'available') {
            return "<span class='btn btn-sm btn-success'> Available </span>";
        }
        if ($value == 'reserved') {
            return "<span class='btn btn-sm btn-danger'> Reserved </span>";
        }
        if ($value == 'switch') {
            return "<span class='btn btn-sm btn-info'> Switch </span>";
        }
        if ($value == 'maintenance') {
            return "<span class='btn btn-sm btn-warning'> Maintenance </span>";
        }
        if ($value == 'destroy') {
            return "<span class='btn btn-sm red'> Destroy </span>";
        }
        if ($value == 'requested') {
            return "<span class='btn btn-sm red'> Requesting </span>";
        }
        else{
            return "<span class='btn btn-sm blue'> Repaired </span>";
        }
    }

}
