<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class MobileApp extends Model
{
    use HasFactory ;

    protected $table = "mobile_apps";

    protected $fillable = ['uuid','detail_id', 'about', 'services', 'price_plan', 'logo', 'offer_image', 'address','notice_image',
        'fb_url', 'google_url', 'youtube_url', 'twitter_url', 'contact_mail', 'banner_image1', 'banner_image2', 'banner_image3'];

    public static $rules = [
        'address' => 'required',
        'services' => 'required',
        'about' => 'required',
        'price_plan' => 'required',
        'contact_mail' => 'required|email|unique:mobile_apps,contact_mail',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }
    public function commonDetails()
    {
        return $this->belongsTo(CommonDetails::class,'detail_id');
    }

}
