<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class PushNotification extends Model
{
    //This model is create to send all the notification to mobile app users only
    use HasFactory, SoftDeletes;

    protected $fillable = ['title','message','url','detail_id','is_default','status'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }
    public static function rules($action)
    {
        $rules = [
            'add'=>[
                'title' => 'required|string|max:255',
                'message' => 'required|string',
                'url' => 'nullable|string',
            ]
        ];
        return $rules[$action];
    }
}
