<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ReviewComment extends Model
{
    use HasFactory,SoftDeletes;

    protected $fillable = ['read_review','comment','merchant_id','client_id','review_id'];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function($apps){
            $uid = uniqid();
            while (self::where('uuid',$uid)->count() > 0) {
                $uid = uniqid();
            }
            $apps->uuid = $uid;
        });
    }

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public static function findByUid($uuid)
    {
        return self::where('uuid',$uuid)->first();
    }

    public static function reviewComments($reviewId,$take,$skip){
        return ReviewComment::where('review_id',$reviewId)->take($take)->get();
    }

    public function merchant(){
        return $this->belongsTo(Merchant::class);
    }
}
